resources:
  - name: small-book
    type: git
    source:
      uri: git@github.com:cf-pub-tools/small-book.git
      branch: master
      private_key: {{private-key}}

  - name: tiny-section
    type: git
    source:
      uri: git@github.com:cf-pub-tools/tiny-section.git
      branch: master
      private_key: {{private-key}}

  - name: credentials
    type: git
    source:
      uri: git@github.com:cf-pub-tools/bookbinder-ci-credentials
      branch: master
      private_key: {{private-key}}

  - name: concourse-scripts
    type: git
    source:
      uri: git@github.com:dyozie/concourse-training-scripts
      branch: master
      private_key: {{private-key}}

jobs:
  - name: staging
    plan:
      - get: small-book
      - get: tiny-section
      - get: credentials
      - get: concourse-scripts
      - task: publish-to-staging
        file: concourse-scripts/publish-to-staging.yml
        privileged: true

  - name: push-to-prod
    plan:
      - get: small-book
      - get: tiny-section
      - get: credentials
      - get: concourse-scripts
      - task: publish-to-staging
        file: concourse-scripts/push-to-prod.yml
        privileged: true


groups:
  - name: <your-team-name>
    jobs:
      - staging
      - push-to-prod
